farmer.o: farmer.cc /usr/class/cs110/include/socket++/sockstream.h \
 block.h txn.h key.h /usr/class/cs110/local/include/exit-utils.h \
 messages.h endpoint.h server-socket.h thread-pool.h utils.h
client-socket.o: client-socket.cc client-socket.h
server-socket.o: server-socket.cc server-socket.h
block.o: block.cc block.h txn.h key.h utils.h
messages.o: messages.cc client-socket.h \
 /usr/class/cs110/local/include/exit-utils.h messages.h \
 /usr/class/cs110/include/socket++/sockstream.h txn.h key.h block.h \
 endpoint.h utils.h
txn.o: txn.cc key.h txn.h utils.h
endpoint.o: endpoint.cc endpoint.h client-socket.h
utils.o: utils.cc utils.h txn.h key.h \
 /usr/class/cs110/local/include/ostreamlock.h
